AgentRoot/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, re_path, include
from .views import *

app_name = 'AgentRoot'

urlpatterns = [
    path('', general_monitor, name='general_monitor'),
    path('loading/', loading_view, name='loading_view'),
    path('not_found/', not_found_view, name='not_found_view'),
    path('flowing/', rc_flowing, name='rc_flowing'),
    path('interval_tables/', check_interval_tables, name='check_interval_tables'),
    path('search/', search_from_nav, name='search_from_nav'),
    path('incidents_home/', incidents_home, name='incidents_home'),
    path('incidents/', incidents_monitor, name='incidents_monitor'),
    path('incidents/diagnosis', diagnosis_monitor, name='diagnosis_monitor'),
    path('log_monitoring/', log_monitoring, name='log_monitoring'),
    path('log_monitoring/all_logs/', log_monitoring_all, name='log_monitoring_all'),
    path('all_logs/', all_logs, name='all_logs'),
    path('atiba/', monitoring_atiba, name='monitoring_atiba'),
    path('atiba/logs', monitoring_atiba_uilogs, name='monitoring_atiba_uilogs'),

    re_path(r'^anomalies/(?P<id>[\w-]+)/$', anomalies_detail_monitor, name='anomalies_detail_monitor'),
    re_path(r'^incidents/(?P<id>[\w-]+)/$', diagnoses_for_incidentset, name='diagnoses_for_incidentset'),
    re_path(r'^incidents/diagnosis/analyse/(?P<id>[\w-]+)/$', diagnosis_analyse, name='diagnosis_analyse'),
]

accounts/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from accounts.views import *

app_name = 'accounts'

urlpatterns = [
    # path('', ),
    # path('register/', accounts_register, name='accounts_register'),
    path('login/', accounts_login, name='accounts_login'),
    path('logout/', accounts_logout, name='accounts_logout'),
    path('change/', accounts_change_password, name='accounts_change_password'),
    path('license/', add_license, name='add_license'),

]

inventories/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from inventories.views import *

app_name = 'inventories'

urlpatterns = [
    path('module/', module_home, name='module_home'),
    path('module/report', module_report, name='module_report'),
    path('module/reports', report_list, name='report_list'),
    path('networks/', networks, name='networks'),
    # path('devices/', network_devices, name='devices'),
    path('monitor/devices/', network_devices, name='devices'),
    path('locations/', locations, name='locations'),
    path('logs/', logs, name='logs'),
    path('anomalies/', anomalies, name='anomalies'),
    # path('anomalies/logs', anomaly_logs, name='anomaly_logs'),
    path('system_users/', system_users, name='system_users'),
    path('root_cause/', rc_graph_list, name='rc_graph_list'),
    path('add_device_driver/', add_device_driver, name='add_device_driver'),

    re_path(r'^networks/(?P<id>[\w-]+)/$', network_detail, name='network_detail'),
    # re_path(r'^devices/(?P<id>[\w-]+)/$', device_detail, name='device_detail'),
    re_path(r'^monitor/devices/(?P<id>[\w-]+)/$', device_detail, name='device_detail'),
    re_path(r'^locations/(?P<id>[\w-]+)/$', location_detail, name='location_detail'),
    re_path(r'^logs/(?P<id>[\w-]+)/$', log_detail, name='log_detail'),
    re_path(r'^logs/log_source/(?P<id>[\w-]+)/$', logs_for_source, name='logs_for_source'),
    re_path(r'^anomalies/(?P<id>[\w-]+)/$', anomaly_detail, name='anomaly_detail'),
    re_path(r'^anomalies/logs/(?P<id>[\w-]+)/$', anomaly_logs, name='anomaly_logs'),
    re_path(r'^root_cause/(?P<id>[\w-]+)/$', rc_graph_detail, name='rc_graph_detail'),
    re_path(r'^module/report/(?P<id>[\w-]+)/$', report_detail, name='report_detail'),
    re_path(r'^module/report/(?P<id>[\w-]+)/delete/', delete_report_type, name='delete_report_type'),

]

AgentRoot/models.py
"""
@author : istiklal
Database models for newly creating report types
"""
import logging

from django.db import models
from django.db.models import Manager
from django.urls import reverse
from django.utils import timezone

logger = logging.getLogger('models')


class ReportBase(models.Model):
    """
    database to save reporting style
    """
    user = models.IntegerField(verbose_name="User ID that select this report type", blank=True, null=True)
    user_group = models.IntegerField(verbose_name="Group ID for licence over user groups", blank=True, null=True)
    report_name = models.TextField(verbose_name="Name that given by user", null=True, blank=True)
    report_format = models.TextField(verbose_name="List formatted report details", blank=True, null=True)
    report_type = models.TextField(verbose_name="List formatted report type details", blank=True, null=True)
    visual_format = models.TextField(verbose_name="Text formatted visual format details", blank=True, null=True)
    home_page = models.BooleanField(verbose_name="Do you want to see this on your home page?", default=False)
    mailing_interval = models.IntegerField(verbose_name="Email sending interval by days, if null ve don't send email",
                                           blank=True, null=True)
    creation_date = models.DateTimeField(verbose_name="Exact date & time report's creation",
                                         default=timezone.now)

    objects = Manager()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.report_name is None or self.report_name == "":
            self.report_name = f"report_{self.user}_{self.user_group}_{self.creation_date}"

    def __str__(self):
        return self.report_format

    def get_absolute_url(self):
        return reverse('inventories:report_detail', kwargs={'id': self.id})

    def get_delete_url(self):
        return reverse('inventories:delete_report_type', kwargs={'id': self.id})

    def name_change(self, name):
        self.report_name = name

    class Meta:
        ordering = ["-id", "user_group", "user", "home_page"]
        unique_together = (('user', 'report_format'),)

AgentRoot/views.py
"""
@author: istiklal
"""
import _thread
import datetime
import json
import locale
import socket
import tracemalloc
# import requests
# from base64 import b64encode
# import dill
# import jsonpickle
# import numpy as np
# from bokeh.embed import components
# from bokeh.plotting import figure, show, output_file
from statistics import mode

import requests
from elasticsearch_dsl import Search
from scipy.stats import gaussian_kde
from django.core import serializers
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.db.models import Count, Func, Max
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.views.decorators.clickjacking import xframe_options_sameorigin
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required

from ATIBAreport.ElasticModels import LogFromElastic, AggregationElastic
from ATIBAreport.decorators import licence_required
from ATIBAreport.graph_generator import hitsListForTest, help_psqlDateTimeFormats, help_psqlStringOps, \
    check_services_result_samples
from ATIBAreport.project_common import *
from ATIBAreport.reachjava import *
from ATIBAreport.setting_files.passes import postgresql_conn_string_prod, postgresql_conn_string_dev, \
    atibaApiService_API_KEY, atibaApiService_PORT
from AgentRoot.forms import *
from accounts.models import *
from inventories.models import *
from inventories.views import template_message_show

locale.setlocale(locale.LC_ALL, locale='tr_TR.utf8')
logger = logging.getLogger('views')
timer = logging.getLogger('timer')
memory_tracer = logging.getLogger('memorytracer')
# logger.setLevel(logging.INFO)

# signal = Signal(providing_args=['signal_data'])
postgresql_conn_string = postgresql_conn_string_prod if check_environment_for_elastic() else postgresql_conn_string_dev
globalBool = True
globalList = []
globalElasticLogList = []
globalAggregation = None

# Home page views in here


@xframe_options_sameorigin
def loading_view(request):
    logger.debug(f"Loading screen appeared..")
    return render(request, "loading.html", {'route': 'atiba_loading'})


@xframe_options_sameorigin
def not_found_view(request):
    logger.debug(f"Not Found screen appeared..")
    return render(request, "loading.html", {'route': 'not_found'})


@login_required
def check_license(request):
    time_triggered = datetime.datetime.now()
    route = ""
    _updt = 0
    _today = datetime.datetime.now()
    is_expired = True
    active_lics = []
    licenseCount = AtibaLicense.objects.count()
    logger.info(f"We got total {licenseCount} license")
    if licenseCount > 0:
        licenseList = AtibaLicense.objects.all()
        for lic in licenseList:
            if not lic.is_converted_python():
                try:
                    _lic_json_string = decode_with_java(lic.licenseStringJava)
                    if _lic_json_string and _lic_json_string != "":
                        _lic_json = json.loads(_lic_json_string)
                        logger.info(f"Got license which is not pythonized : ({_lic_json})")
                        _expiration = datetime.datetime.strptime(_lic_json["atiba-license"]["exp_date"], "%d-%m-%Y")
                        lic.licenseStringPython = atiba_encrypt(json.dumps(_lic_json))
                        try:
                            if _expiration and (_expiration - _today).days > 0:
                                is_expired = False
                                lic.isExpired = False
                                active_lics.append(lic)
                            else:
                                lic.isExpired = True

                            lic.save()

                        except Exception as err:
                            logger.exception(f"An error occurred trying to save lic. ERROR IS : {err}")
                except Exception as err:
                    logger.exception(
                        f"An error occurred in check_license view trying to decode_with_java. ERROR IS : {err}")

            else:
                if lic.lictype is None:
                    _updt += AtibaLicense.objects.filter(id=lic.id).update(lictype=lic.get_license_type())

                if lic.lictype == 'permanent':
                    is_expired = False
                    active_lics.append(lic)

                _expiration = lic.get_license_expiration()
                if _expiration and (_expiration - _today).days > 0:
                    if lic.isExpired is None:
                        _updt += AtibaLicense.objects.filter(id=lic.id).update(isExpired=False)
                    is_expired = lic.isExpired if lic.isExpired else False
                    active_lics.append(lic)

                if check_environment_for_production() and not lic.is_license_valid():
                    if lic.failoverdate:
                        # it means that master is down on this date, and machine running on back-up node. Let the
                        # license work for 15 days
                        _failing_days = (time_triggered.date() - lic.failoverdate).days
                        if _failing_days < 15:
                            logger.critical(f"SYSTEM IS WORKING ON A SLAVE NODE FOR {_failing_days} DAYS, "
                                            f"IMMEDIATELY RETURN TO MASTER NODE !!")
                            template_message_show(request,
                                                  "error",
                                                  f"System is working in recovery mode for {_failing_days} days")
                        else:
                            logger.warning(f"SYSTEM DO NOT MATCH LICENSE : {lic.id}")
                            _updt += AtibaLicense.objects.filter(id=lic.id).update(isExpired=True)

        logger.info(f"lic update count is : {_updt}")
        logger.info(f"active license count is : {len(active_lics)}")
        # logger.debug(f"is_expired is : {is_expired}")

        if len(active_lics) > 0 and not is_expired:
            timer.debug(f"{(datetime.datetime.now() - time_triggered).total_seconds()}")
            return redirect('home')
        else:
            # send to new license form
            route = "LICENSE EXPIRED"
            logger.warning("LICENSE EXPIRED")
            timer.debug(f"{(datetime.datetime.now() - time_triggered).total_seconds()}")
            return redirect('accounts:add_license')
    else:
        # send to new license form
        route = "NO LICENSE"
        logger.warning("NO LICENSE")
        timer.debug(f"{(datetime.datetime.now() - time_triggered).total_seconds()}")
        return redirect('accounts:add_license')

    # context = {
    #     'route': route,
    # }

    # return render(request, 'accounts/register_and_login.html', {'route': route})


def error_pages(request, **kwargs):
    if kwargs:
        logger.debug(f"we got parameters : {kwargs}")
    route = None
    warning = None
    myLogList = []

    context = {
        "route": route, "warning": warning, "myLogList": myLogList,
    }
    return render(request, 'errors.html', context)


@licence_required
@xframe_options_sameorigin
def home_view(request):
    time_triggered = datetime.datetime.now()
    _today = datetime.date.today()
    startDate = _today-datetime.timedelta(days=6)
    startDateString = startDate.strftime("%Y-%m-%d")
    endDate = _today
    endDateString = _today.strftime("%Y-%m-%d")
    logger.info(f"TODAY : {_today}")
    logger.info(f"USER IS : {request.user}")
    # _usersCount = User.objects.filter(is_djangoUser=True).count()

    if check_psql_is_recovery():
        return redirect('cluster')

    # GREETING PAGE CONTROL
    try:
        referer = request.META['HTTP_REFERER']
        logger.debug(f"Request from internal guest : {referer} in port {request.META['SERVER_PORT']}")
    except Exception as err:
        logger.warning(f"Request from external guest : {err} in port {request.META['SERVER_PORT']}")
        timer.debug(f"{(datetime.datetime.now()-time_triggered).total_seconds()}")
        return render(request, 'greeting.html')

    # CHECKING PSQL, ELASTIC CONNECTIONS AND HEALTH INFO
    elastic_health = check_elastic_health()
    psql_health = check_psql_health()
    if not elastic_health or not psql_health:
        errorDay = datetime.date.today()
        myLogList = read_your_own_logs(end_date=errorDay, start_date=errorDay)[0]
        myLogList = [_ for _ in myLogList if _.startswith("[ERROR") or _.startswith("[WARNING")]
        myLogList.reverse()
        if not elastic_health and not psql_health:
            cause = "database"
            explanation = f"Errors in both Postgresql and Elacticsearch connection"
            # return redirect('error_pages')
            return render(request, 'errors.html', {"route": cause, "warning": explanation, "myLogList": myLogList})

        elif not psql_health:
            cause = "database"
            explanation = f"Errors in Postgresql connection"
            # return redirect('error_pages')
            return render(request, 'errors.html', {"route": cause, "warning": explanation, "myLogList": myLogList})

        elif not elastic_health:
            cause = "database"
            explanation = f"There are problems in Elacticsearch connection"
            # return redirect('error_pages')
            return render(request, 'errors.html', {"route": cause, "warning": explanation, "myLogList": myLogList})

    # USER LOGIN CONTROL
    # if _usersCount == 0 and not request.user.is_authenticated:
    #     return redirect('accounts:accounts_register')
    if not request.user.is_authenticated:
        timer.debug(f"{(datetime.datetime.now() - time_triggered).total_seconds()}")
        return redirect('accounts:accounts_login')

    # CHECKING PSQL IS IN RECOVERY MODE OR NOT. IF RESULT IS TRUE THEN WE ARE IN SLAVE NODE !!!
    isPSQLrecovery = check_psql_is_recovery()
    if isPSQLrecovery:

templates/AgentRoot/edit_parameters.html
<!DOCTYPE html>
{% load static %}
<html lang="en-US">
    <head>

        <meta http-equiv="content-type" content="text/html charset=UTF-8" />
        <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1.0" />

        <title> Log Definition Details </title>

        <link rel="icon" href="{% static 'img/favicon.png' %}">
        <link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link type="text/css" rel="stylesheet" href="{% static 'css/general_style.css' %}">
    </head>
    <body  style="padding-top:15px;">

        {% if route == 'general' %}


        {% elif route == 'detail' %}

        <div class="container-fluid" style="text-align:center;font-size:9pt;">
            <h5>id : {{logDefDetail.id}} / {{logDefDetail.logcode}}</h5>

            <div class="row" style="margin:10px;">
                <form method="POST" name="reparse_all">
                    {%csrf_token%}
                    <button type="submit" class="btn btn-sm btn-outline-danger" style="font-size:9pt;"
                            value="{{logDefDetail.logcode}}" id="reparse_all" name="reparse_all">
                        Re-Parse All
                    </button>
                </form>
                <form method="POST" name="reparse_selected">
                    {%csrf_token%}
                    <button type="submit" class="btn btn-sm btn-outline-danger"
                            style="font-size:9pt;margin-left:10px;" value="" id="reparse_selected"
                            name="reparse_selected">
                        Re-Parse Selected
                    </button>
                </form>
                <form method="POST" name="analyse_parameter">
                    {%csrf_token%}
                    <button type="submit" class="btn btn-sm btn-outline-secondary"
                            style="font-size:9pt;margin-left:10px;" value="" id="analyse_parameter"
                            name="analyse_parameter">
                        Analyse Parameter
                    </button>
                </form>
            </div>

            <br>

            <div class="row" style="margin:10px;">
                <div class="col-md-9">
                    <div class="row">
                        <h5>Definition Structure</h5>
                    </div>
                    <br>
                    <div class="row">
                        {{logDefDetail.logstructs}}
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="row">
                        <button class="btn btn-outline-info btn-sm"
                                name="{{anomaly.get_type_definition}}"
                                onclick="create_frame_url(this)" id="{{anomaly.id}}" title="EDIT PARAMETERS"
                                data-toggle="modal" data-target="#modal_edit_params"
                                style="font-size:9pt;">
                            Edit Parameters
                        </button>
                        <form method="POST" name="paramsvalid">
                            {%csrf_token%}
                            <button type="submit" class="btn btn-sm btn-outline-secondary"
                                    style="font-size:9pt;margin-left:10px;" value="True" id="paramsvalid"
                                    name="paramsvalid">
                                Validate
                            </button>
                        </form>
                    </div>
                </div>
            </div>

        </div>

        {% else %}

         <div class="container" style="text-align:center;">
            <h5>SOON ...</h5>
            <hr>
         </div>

        {% endif %}

        <div class="container" style="position:fixed;bottom:0.1%;left:2%;width:30%;zoom:0.75">
            <small>{% include 'messages.html' %}</small>
        </div>

        <script type="text/javascript" language="JavaScript" src="{% static 'js/jquery.min.js' %}"></script>
        <script type="text/javascript" language="JavaScript" src="{% static 'js/bootstrap.min.js' %}"></script>
        <script type="text/javascript" language="JavaScript" src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
        <script type="text/javascript" language="JavaScript">
            function create_frame_url(button) {
                var frame = document.getElementById('anomaly_detail_frame');
                var anomaly_id = button.id;
                document.getElementById('modalLabel').innerHTML = anomaly_id+" - "+button.name;
                //console.log(document.getElementById('modalLabel'));
                //console.log(frame);
                //console.log(frame.src);
                //console.log(anomaly_id);
                frame.src = window.location.origin+"/monitor/anomalies/"+anomaly_id;
                console.log(frame.src);
                console.log(window.location.origin);
            }
        </script>
    </body>

</html>

templates/AgentRoot/elastic_logs.html
{% extends 'base.html' %}
{% load static %}

<link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

{% block titleBlock %}

    All Logs {{ block.super }}

{% endblock %}

{% block bodyBlock %}


{% if route == "general" %}

<div class="container-fluid innerBodies">
    <h5>ALL COLLECTED LOGS</h5>
    <div class="row justify-content-center innerBodies">
        <div class="col col-xl-6 col-lg-8 col-md-12 col-sm-12" align="center" name="charts">
            <canvas id="chart_all_logs" title="Log Counts"></canvas>
            <hr/>
            <data id="{{all_logs_chart_labels}}" value="{{all_logs_chart_values}}" style="display:none;">logs_bar</data>
        </div>
    </div>
    <form method="GET" enctype="multipart/form-data">
        <div class="row justify-content-center">

            <div class="col col-xl-5 col-lg-6 col-md-8 col-sm-12" style="border-left:0.5px solid grey;border-right:0.5px solid grey;">
                Select a Date Time Interval <span style="padding-left:20px;"><small>(logs in {{interval_in_hours}} hours interval selected)</small></span>
                <hr>
                <small>
                    <label for="from_date">From : </label>
                    <input id="from_date" type="datetime-local" name="fromDate_q" value="{% if request.GET %}{{request.GET.fromDate_q}}{% else %}{{yesterday}}{% endif %}" />
                </small>
                <small>
                    <label for="to_date">To : </label>
                    <input id="to_date" type="datetime-local" name="toDate_q" value="{% if request.GET %}{{request.GET.toDate_q}}{% else %}{{today}}{% endif %}" />
                </small>

            </div>
            <div class="col col-xl-2 col-lg-2 col-md-8 col-sm-12" style="border-left:0.5px solid grey;border-right:0.5px solid grey;">
                Select a Log Source
                <hr>
                <small>
                    <select name="device_q">
                        <option value="">Select a log source</option>
                        {% for device in deviceList %}
                        <option value="{{device.uniqueid}}" {%if request.GET.device_q == device.uniqueid%}selected{%endif%}>{{device.uniqueid}}</option>
                        {% endfor %}
                    </select>
                </small>
            </div>
            <div class="col col-xl-2 col-lg-2 col-md-8 col-sm-12" style="border-left:0.5px solid grey;border-right:0.5px solid grey;">
                Limit Record Count
                <hr>
                <small>
                    <input type="number" name="limit_q" placeholder="Limit of count" value="{{request.GET.limit_q}}" />
                </small>
            </div>
            <div class="col col-xl-2 col-lg-2 col-md-8 col-sm-12" style="border-left:0.5px solid grey;border-right:0.5px solid grey;">
                <small>
                    <input type="text" name="event_q" placeholder="Search in logs" value="{{request.GET.event_q}}" />
                </small>
                <hr>
                <small>
                    <a class="asLink" href="{% url 'AgentRoot:all_logs' %}" style="text-decoration:None;">Clear All Searches</a>
                    <button style="display:block;float:right;height:21px;width:50px;padding:0;overflow:hidden;" class="btn btn-outline-success btn-sm" type="submit"><small>&#8981;</small></button>
                </small>
            </div>

        </div>
    </form>
    <hr/>
    <small>
        <div class="col-lg-9 col-md-8 col-sm-7 col-6" style="position:relative;float:left;">last {{ caption }} in {{filtered_count}} of total {{totalCount}}</div>
        <table class="table table-sm table-hover">
    <!--            <caption>{{ caption }} (TOTAL : {{totalCount}})</caption>-->
            <thead class="thead-light">
                <tr>
                    <th>IP</th>
                    <th>LOG CODE</th>
    <!--                    <th>RAW LOG</th>-->
                    <th>DATE</th>
                    <th>LOG EVENT</th>
                </tr>
            </thead>
            <tbody>
                {% for log in logList %}
                <tr>
                    <td><small><a href="#">{{ log.inetaddress }}</a></small></td>
                    <td><small>{{ log.logndx }}</small></td>
    <!--                    <td><small>{{ log.logdata }}</small></td>-->
    <!--                    <td><small>{{ log.source }}</small></td>-->
                    <td><small>{{ log.credate }}</small></td>
                    <td><small>{{ log.event }}</small></td>
    <!--                    <td>{% if  log.userdisabled == True %}&#x2713;{% else %}&#x2717;{% endif %}</td>-->

                </tr>
                {% endfor %}
            </tbody>

        </table>

        <hr />

        <div class="pagination">{# my pagination #}
            <span class="step-links">
                {% if request.GET.page_q and request.GET.page_q != '1' %}
                    <a href="?page_q=1{% if request.GET %}&limit_q={{request.GET.limit_q}}&fromDate_q={{request.GET.fromDate_q}}&toDate_q={{request.GET.toDate_q}}&device_q={{request.GET.device_q}}&event_q={{request.GET.event_q}}{% endif %}">&laquo; jump to first </a>/
                    <a href="?page_q={{ request.GET.page_q|add:-1 }}{% if request.GET %}&limit_q={{request.GET.limit_q}}&fromDate_q={{request.GET.fromDate_q}}&toDate_q={{request.GET.toDate_q}}&device_q={{request.GET.device_q}}&event_q={{request.GET.event_q}}{% endif %}"> previous </a>/
                {% endif %}
                <span class="current">
                    {% if request.GET.page_q and request.GET.page_q != '' %}
                    <i>{{request.GET.page_q}}. of {{ totalPages }} pages </i>
                    {% else %}
                    <i>1. of {{ totalPages }} pages </i>
                    {% endif %}
                </span>
                {% if request.GET.page_q != totalPagesString and totalPages != 1 %}
                    {% if request.GET.page_q and request.GET.page_q != '' %}
                        /<a href="?page_q={{ request.GET.page_q|add:1 }}{% if request.GET %}&limit_q={{request.GET.limit_q}}&fromDate_q={{request.GET.fromDate_q}}&toDate_q={{request.GET.toDate_q}}&device_q={{request.GET.device_q}}&event_q={{request.GET.event_q}}{% endif %}"> next </a>
                        /<a href="?page_q={{totalPages}}{% if request.GET %}&limit_q={{request.GET.limit_q}}&fromDate_q={{request.GET.fromDate_q}}&toDate_q={{request.GET.toDate_q}}&device_q={{request.GET.device_q}}&event_q={{request.GET.event_q}}{% endif %}"> jump to last &raquo;</a>
                    {% else %}
                        /<a href="?page_q=2{% if request.GET %}&limit_q={{request.GET.limit_q}}&fromDate_q={{request.GET.fromDate_q}}&toDate_q={{request.GET.toDate_q}}&device_q={{request.GET.device_q}}&event_q={{request.GET.event_q}}{% endif %}"> next </a>
                        /<a href="?page_q={{totalPages}}{% if request.GET %}&limit_q={{request.GET.limit_q}}&fromDate_q={{request.GET.fromDate_q}}&toDate_q={{request.GET.toDate_q}}&device_q={{request.GET.device_q}}&event_q={{request.GET.event_q}}{% endif %}"> jump to last &raquo;</a>
                    {% endif %}
                {% endif %}
            </span>
        </div>{# /my pagination #}

    </small>
</div>



{% elif route == "detail" %}

<div class="container-fluid innerBodies">
    <table class="table table-striped table-sm table-hover">
        <caption>{{ caption }}</caption>
        <thead class="thead-light">
            <tr>
                <th>IP Address & Port</th>
                <th>{{ log.inetaddress }} : {{ log.port }}</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Log Code</td>
                <td>{{ log.logno }}</td>
            </tr>
            <tr>
                <td>Log Device Name</td>
                <td>{{ log.devicename }}</td>
            </tr>
            <tr>
                <td>Log Date</td>
                <td>{{ log.olusturmatarih }}</td>
            </tr>
            <tr>
                <td>Log Event</td>
                <td>{{  log.logevent }}</td>
            </tr>
            <tr>
                <td>Log Severity</td>
                <td>{{ log.severity}}</td>
            </tr>
            <tr>
                <td>Raw Log</td>
                <td>{{ log.logdata }}</td>
            </tr>
        </tbody>
    </table>

    <div></div>
    <div><a href="{% url 'inventories:logs' %}"> BACK TO LOGS </a></div>

</div>


{% endif %}





{% endblock %}