AgentRoot/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, re_path, include
from .views import *

app_name = 'AgentRoot'

urlpatterns = [
    path('', general_monitor, name='general_monitor'),
    path('loading/', loading_view, name='loading_view'),
    path('not_found/', not_found_view, name='not_found_view'),
    path('flowing/', rc_flowing, name='rc_flowing'),
    path('interval_tables/', check_interval_tables, name='check_interval_tables'),
    path('search/', search_from_nav, name='search_from_nav'),
    path('incidents_home/', incidents_home, name='incidents_home'),
    path('incidents/', incidents_monitor, name='incidents_monitor'),
    path('incidents/diagnosis', diagnosis_monitor, name='diagnosis_monitor'),
    path('log_monitoring/', log_monitoring, name='log_monitoring'),
    path('log_monitoring/all_logs/', log_monitoring_all, name='log_monitoring_all'),
    path('all_logs/', all_logs, name='all_logs'),
    path('atiba/', monitoring_atiba, name='monitoring_atiba'),
    path('atiba/logs', monitoring_atiba_uilogs, name='monitoring_atiba_uilogs'),

    re_path(r'^anomalies/(?P<id>[\w-]+)/$', anomalies_detail_monitor, name='anomalies_detail_monitor'),
    re_path(r'^incidents/(?P<id>[\w-]+)/$', diagnoses_for_incidentset, name='diagnoses_for_incidentset'),
    re_path(r'^incidents/diagnosis/analyse/(?P<id>[\w-]+)/$', diagnosis_analyse, name='diagnosis_analyse'),
]

accounts/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from accounts.views import *

app_name = 'accounts'

urlpatterns = [
    # path('', ),
    # path('register/', accounts_register, name='accounts_register'),
    path('login/', accounts_login, name='accounts_login'),
    path('logout/', accounts_logout, name='accounts_logout'),
    path('change/', accounts_change_password, name='accounts_change_password'),
    path('license/', add_license, name='add_license'),

]

inventories/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from inventories.views import *

app_name = 'inventories'

urlpatterns = [
    path('module/', module_home, name='module_home'),
    path('module/report', module_report, name='module_report'),
    path('module/reports', report_list, name='report_list'),
    path('networks/', networks, name='networks'),
    # path('devices/', network_devices, name='devices'),
    path('monitor/devices/', network_devices, name='devices'),
    path('locations/', locations, name='locations'),
    path('logs/', logs, name='logs'),
    path('anomalies/', anomalies, name='anomalies'),
    # path('anomalies/logs', anomaly_logs, name='anomaly_logs'),
    path('system_users/', system_users, name='system_users'),
    path('root_cause/', rc_graph_list, name='rc_graph_list'),
    path('add_device_driver/', add_device_driver, name='add_device_driver'),

    re_path(r'^networks/(?P<id>[\w-]+)/$', network_detail, name='network_detail'),
    # re_path(r'^devices/(?P<id>[\w-]+)/$', device_detail, name='device_detail'),
    re_path(r'^monitor/devices/(?P<id>[\w-]+)/$', device_detail, name='device_detail'),
    re_path(r'^locations/(?P<id>[\w-]+)/$', location_detail, name='location_detail'),
    re_path(r'^logs/(?P<id>[\w-]+)/$', log_detail, name='log_detail'),
    re_path(r'^logs/log_source/(?P<id>[\w-]+)/$', logs_for_source, name='logs_for_source'),
    re_path(r'^anomalies/(?P<id>[\w-]+)/$', anomaly_detail, name='anomaly_detail'),
    re_path(r'^anomalies/logs/(?P<id>[\w-]+)/$', anomaly_logs, name='anomaly_logs'),
    re_path(r'^root_cause/(?P<id>[\w-]+)/$', rc_graph_detail, name='rc_graph_detail'),
    re_path(r'^module/report/(?P<id>[\w-]+)/$', report_detail, name='report_detail'),
    re_path(r'^module/report/(?P<id>[\w-]+)/delete/', delete_report_type, name='delete_report_type'),

]

templates/ai_sensitivity.html
<!DOCTYPE html>
{% load static %}
<html lang="en-US">
    <head>
        <meta http-equiv="content-type" content="text/html charset=UTF-8" />
        <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1.0" />

        <title> ATIBAreport - AI Sensitivity Settings </title>

        <link rel="icon" href="{% static 'img/favicon.png' %}">
        <link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link type="text/css" rel="stylesheet" href="{% static 'css/general_style.css' %}">
        <style>

        </style>
    </head>
    <body>

        <div id="loading"><!-- LOADING PART -->
            <div class="container-fluid" id="atiba_loading">
                <h2 class="atiba_loading_h">ΛTIBΛ</h2>
            </div>
        </div><!-- / LOADING PART -->

        <div class="container-fluid" id="page" style="margin:0;padding:0;"><!-- PAGE PART -->
            <h5 align="center">SENSITIVITY SETTINGS</h5>
<!--            {% for x in algorithms %}<p>{{x}}</p>{% endfor %}-->
            <hr>
            <div class="container-fluid" name="formContainer">
                <form method="POST" action="{%url 'ai_sensitivity'%}" name="ai_sensitivity_form" onkeydown="return event.key != 'Enter';">
                    {% csrf_token %}
                    {% for x in algorithms %}
                        <div class="form-group row justify-content-center">
                            <label for="input{{x.id}}" id="label{{x.id}}" class="col-md-4"><b>{{x.algorithmname}}</b> Sensitivity</label>
                            <div class="col-md-3" align="center">
                                <a type="button" class="btn btn-sm btn-outline-danger"
                                   onclick="document.getElementById('input{{x.id}}').value=-1;document.getElementById('label{{x.id}}').style.color='rgba(255, 99, 132, 0.85)';">
                                    Less Sensitive (-)
                                </a>
                            </div>
                            <div class="col-md-2" align="center" style="display:none">
                                <input class="form-control form-control-sm" type="number" id="input{{x.id}}" name="{{x.id}}" min="-1" max="1" value="{{x.val}}" />
                            </div>
                            <div class="col-md-3" align="center">
                                <a type="button" class="btn btn-sm btn-outline-success"
                                   onclick="document.getElementById('input{{x.id}}').value=1;document.getElementById('label{{x.id}}').style.color='rgba(75, 192, 192, 0.85)';">
                                    More Sensitive (+)
                                </a>
                            </div>
                        </div>
                    {% endfor %}
                    <hr>
                    <div class="form-group row justify-content-center">
                        <div class="col-md-4"align="center">
                            <a class="btn btn-outline-danger btn-sm" type="button" style="width:100%;" onclick="location.assign(location.href);">RESET CHANGES</a>
                        </div>
<!--                        <div class="col-md-1"></div>-->
                        <div class="col-md-6" align="center">
                            <button class="btn btn-outline-info btn-sm" type="submit" style="width:100%;">APPLY CHANGES</button>
                        </div>
                    </div>
                </form>
            </div>

            <div class="container" style="position:fixed;bottom:0.1%;left:2%;width:30%;zoom:0.75">
                <small>{% include 'messages.html' %}</small>
            </div>

        </div> <!-- / PAGE PART -->


        <script type="text/javascript" language="JavaScript" src="{% static 'js/jquery.min.js' %}"></script>
        <script type="text/javascript" language="JavaScript" src="{% static 'js/bootstrap.min.js' %}"></script>
        <script type="text/javascript" language="JavaScript" src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
        <script type="text/javascript" language="JavaScript">
            // colors -> [green, red, orange, blue, yellow, grey, purple]
            var graphColors = ['rgba(75, 192, 192, 0.85)','rgba(255, 99, 132, 0.85)','rgba(255, 159, 64, 0.85)','rgba(54, 162, 235, 0.85)','rgba(255, 206, 86, 0.85)','rgba(150, 150, 150, 0.85)','rgba(106, 92, 112, 0.85)']
            var labelNames = ['Alert ', 'Cause ', 'Sub']

            $(document).ready(function () {
                $("#loading").hide();
                $("#page").show();
                $(".alert").fadeTo(8000, 0);
                setTimeout(function () {$(".alert").alert("close")}, 10000);
            });

        </script>
    </body>
</html>

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en-US">
    <head>

        <meta http-equiv="content-type" content="text/html charset=UTF-8" />
        <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1.0" />

        <link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link type="text/css" rel="stylesheet" href="{% static 'css/general_style.css' %}">
        <link type="text/css" rel="stylesheet" href="{% static 'css/Chart.min.css' %}">

        <title> ATIBAreport - {% block titleBlock %}  {% endblock %} </title>

<!--        <link rel="icon" href="{% static 'img/favicon.png' %}">-->
<!--        <link rel="icon" href="{% static 'img/favicons/favicon.png' %}">-->

        <!-- All about favicons-->
        <link rel="apple-touch-icon" sizes="57x57" href="{% static 'img/favicons/apple-icon-57x57.png' %}">
        <link rel="apple-touch-icon" sizes="60x60" href="{% static 'img/favicons/apple-icon-60x60.png' %}">
        <link rel="apple-touch-icon" sizes="72x72" href="{% static 'img/favicons/apple-icon-72x72.png' %}">
        <link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/favicons/apple-icon-76x76.png' %}">
        <link rel="apple-touch-icon" sizes="114x114" href="{% static 'img/favicons/apple-icon-114x114.png' %}">
        <link rel="apple-touch-icon" sizes="120x120" href="{% static 'img/favicons/apple-icon-120x120.png' %}">
        <link rel="apple-touch-icon" sizes="144x144" href="{% static 'img/favicons/apple-icon-144x144.png' %}">
        <link rel="apple-touch-icon" sizes="152x152" href="{% static 'img/favicons/apple-icon-152x152.png' %}">
        <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/favicons/apple-icon-180x180.png' %}">
        <link rel="icon" type="image/png" sizes="192x192"  href="{% static 'img/favicons/android-icon-192x192.png' %}">
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicons/favicon-32x32.png' %}">
        <link rel="icon" type="image/png" sizes="96x96" href="{% static 'img/favicons/favicon-96x96.png' %}">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicons/favicon-16x16.png' %}">
        <link rel="manifest" href="{% static 'img/favicons/manifest.json' %}">
        <meta name="msapplication-TileColor" content="#ffffff">
        <meta name="msapplication-TileImage" content="{% static 'img/favicons/ms-icon-144x144.png' %}">
        <meta name="theme-color" content="#ffffff">



    </head>
    <body>
        <script type="text/javascript" language="JavaScript" src="{% static 'js/jquery.min.js' %}"></script>

        {% include 'schema.html' %}

        <div class="contentViewport">

            <div class="container-fluid innerBodies" id="loading" style="display:block;">
                <div class="container-fluid" id="atiba_loading">
                    <h2 class="atiba_loading_h">ΛTIBΛ</h2>
                </div>
            </div>

            <div id="page" style="display:none;">
                {% include 'news.html' %}
                {% block bodyBlock %}



                {% endblock %}
            </div>

        </div>


        <div class="container" style="position:fixed;bottom:0.1%;left:2%;width:30%;zoom:0.75">
            <small>{% include 'messages.html' %}</small>
        </div>

        {% if request.path != '/' %}
            <hr />
            <div class="container-fluid innerBodies" id="floating_button">
                <button class="btn pmd-btn-fab pmd-ripple-effect btn-outline-secondary floating-left" title="GO BACK"
                        id="floating_back_button" type="button" onclick="window.history.back()">
                    ❮&#10094;
                </button>
<!--                we can use breadcrumbs -->
<!--                <span id="url_map">{{ request.path }}</span>-->
            </div>
        {% endif %}

<!--        <script type="text/javascript" language="JavaScript" src="{% static 'js/jquery.min.js' %}"></script>-->
        <script type="text/javascript" language="JavaScript" src="{% static 'js/bootstrap.min.js' %}"></script>
        <script type="text/javascript" language="JavaScript" src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
        <script type="text/javascript" language="JavaScript" src="{% static 'js/Chart.js' %}"></script>
        <script type="text/javascript" language="JavaScript" src="{% static 'js/general_style.js' %}"></script>
        <script type="text/javascript" language="JavaScript">
            console.log("Active browser : "+getClientBrowserName());
            $(function () {
              $('[data-toggle="tooltip"]').tooltip()
            })

            $(document).ready(function () {
                $("#loading").hide();
                $("#page").show();
            });
        </script>

    </body>
    <footer>
        <noscript>
            In order to use the application, you must enable javascript in your browser's settings.
        </noscript>
        <div id="footer-content">
            {% block footerBlock %}
            {% include 'footer.html' %}
            {% endblock %}
        </div>
    </footer>

</html>

templates/errors.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta http-equiv="content-type" content="text/html charset=UTF-8" />
        <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1.0" />

        <title> ERROR - {{ route|default:"" }} </title>

        <link rel="icon" href="{% static 'img/favicon.png' %}">
        <link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link type="text/css" rel="stylesheet" href="{% static 'css/general_style.css' %}">
</head>
<body>
    <div class="container my-3">
        <h1 align="center">ΛTIBΛ</h1>
        <hr>
        {% if route == "requirements" %}
            <h4 align="center">There are deficiencies in the requirements of the system working environment</h4>
            <hr>
            <p>{{ warning|default:"" }}</p>
            <p>
                <span>You can see the </span>
                <span class="asLink" onclick="get_error_logs_page()">error logs</span>
            </p>
        {% elif route == "database" %}
            <h4 align="center">There are deficiencies in system data storage requirements</h4>
            <hr>
            <p>{{ warning|default:"" }}</p>
            {% if "sql" in warning %}
                <p></p>
            {% else %}
                <p>
                    <span>You can see the </span>
                    <span class="asLink" onclick="get_error_logs_page()">error logs</span>
                    <br>
                    <span>Also you can see below errors and warnings occurred on today</span>
                </p>
            {% endif %}

        {% else %}
            <h4 align="center">System stopped working due to some errors</h4>
            <hr>
            <p>{{ warning|default:"" }}</p>
            <p>
                I'm trying to detect the root-cause of error ...
            </p>
        {% endif %}
        <hr>
        <p>&#x26A0; <a class="asLink" href="{% url 'iamatiba_services' %}" target="_blank"> Click to go service maintenance menu</a></p>
        <hr>
        {% if myLogList %}
            <ul>
               {% for log in myLogList %}
                    {% if log|slice:":2" in "[ER" %}
                        <li style="color:red;">{{ log }}</li>
                    {% elif log|slice:":2" in "[W" %}
                        <li style="color:orange;">{{ log }}</li>
                    {% endif %}
                {% endfor %}
            </ul>

        {% endif %}

    </div>

    <script lang="javascript" type="text/javascript">
        function get_error_logs_page() {
            window.location.assign(window.location.origin+"/monitor/atiba/uilogs?pri_filter=ERROR");
        }
    </script>
</body>
</html>

templates/exceptions.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta http-equiv="content-type" content="text/html charset=UTF-8" />
        <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1.0" />

        <title> Exception - {{ route }} </title>

        <link rel="icon" href="{% static 'img/favicon.png' %}">
        <link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link type="text/css" rel="stylesheet" href="{% static 'css/general_style.css' %}">
</head>
<body>
    <div class="container my-3">
        <h1 align="center">ΛTIBΛ</h1>
        <hr>
        <h4 align="center">{{ warning }}</h4>
        <hr>
    </div>
</body>
</html>

templates/footer.html
<span> ΛTIBΛ LOG by Camenta Systems </span>

templates/home.html
{% extends 'base.html' %}

{% block titleBlock %}

     Home {{ block.super }}

{% endblock %}


{% block bodyBlock %}

<div class="innerBodies container-fluid" style="padding-top:10px;font-size:9pt;">

    <div class="row justify-content-center" id="inventoriesChartsHeader">
        <div class="col-md-11 col-sm-5"><legend>General Information About Given Environment</legend></div>
        <div class="col-md-1 col-sm-1">
<!--                <small>-->
<!--                    <select name="chartType" onchange="changeCharts(this.value)">-->
<!--                        <option value="doughnut">Doughnut Chart</option>-->
<!--                        <option value="bar">Bar Chart</option>-->
<!--                    </select>-->
<!--                </small>-->
            <span style="padding:2px;"></span>
            <button class="btn btn-sm btn-outline-secondary circle" name="inventoriesChart2"
                    id="inventoriesChartButton" onclick="open_close(this)" title="See Content">
<!--                        &#10094;-->
<!--                    &#x002B;-->
                    &#8722;
            </button>
        </div>
    </div>
    <br />
    <div class="container-fluid" style="border-radius:5px;">
        <div class="row justify-content-around" id="systemOverview">
            {% for element in overViewData %}
                <div class="col-md-2 col-sm-12 shadowBox" style="background-color:#ffffff;">
                    <div class="row justify-content-center"><h6 align="center" style="border-bottom: 0.5px solid grey;">{{element.0}}</h6></div>
                    <div class="row justify-content-center"><h6>{{element.1}}</h6></div>
                </div>
            {% endfor %}
        </div>
    </div>
    <hr>
    <br />
    <div class="container-fluid" id="inventoriesChartDiv">
        <div class="row" name="homeScreen" id="inventoriesChart1">
            <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12 shadowBox" style="border-right: 1px solid black;" align="center" name="charts">
                <canvas id="chartDevice" title="TOTAL COUNT"></canvas>
                <hr/>
                <a class="asLink" href="{% url 'inventories:devices' %}" title="Monitoring Devices">LOG SOURCE STATUS</a>
                <data id="{{device_chart_labels}}" value="{{device_chart_values}}" style="display:none;">doughnut</data>
            </div>
            <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12 shadowBox" style="border-right: 1px solid black;" align="center" name="charts">
                <canvas id="chartSources"></canvas>
                <hr/>
                <a class="asLink" href="{% url 'log_sources' %}" title="Log Sources">LOG SOURCE VENDORS</a>
                <data id="{{sources_chart_labels}}" value="{{sources_chart_values}}" style="display:none;">doughnut_empty</data>
            </div>
<!--                <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12" style="border-right: 1px solid black;" align="center" name="charts">-->
<!--                    <canvas id="chartLogsElastic"></canvas>-->
<!--                    <hr/>-->
<!--                    <a class="asLink" href="{% url 'AgentRoot:log_monitoring' %}" title="Monitoring All Logs">TOTAL LOGS COLLECTED</a>-->
<!--                    <data id="{{LogsElastic_chart_labels}}" value="{{LogsElastic_chart_values}}" style="display:none;">doughnut</data>-->
<!--                </div>-->
            <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12 shadowBox" style="border-right: 1px solid black;" align="center" name="charts">
                <canvas id="weeklyLogs"></canvas>
                <hr/>
                <a class="asLink" href="{% url 'AgentRoot:log_monitoring' %}" title="Monitoring All Logs">LOGS IN LAST 7 DAYS</a>
                <data id="{{weeklyLogs_chart_labels}}" value="{{weeklyLogs_chart_values}}" style="display:none;">logs_bar</data>
            </div>
            <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12 shadowBox" style="border-right: 1px solid black;" align="center" name="charts">
                <canvas id="chartLogs" title="Brands"></canvas>
                <hr/>
                <a class="asLink" href="{% url 'inventories:logs' %}" title="Logs in Queue">UNPARSED & QUEUED LOGS</a>
                <data id="{{log_chart_labels}}" value="{{log_chart_values}}" style="display:none;">doughnut</data>
            </div>

        </div>

        <br>

        <div class="row" name="homeScreen" id="inventoriesChart2">
            <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12 shadowBox" style="border-right: 1px solid black;" align="center" name="charts">
                <canvas id="chartRC"></canvas>
                <hr/>
                <a class="asLink" href="{% url 'AgentRoot:diagnosis_monitor' %}" target="_blank" title="Incidents and Details">DIAGNOSES</a>
                <data id="{{rc_chart_labels}}" value="{{rc_chart_values}}" style="display:none;">doughnut</data>
            </div>
            <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12 shadowBox" style="border-right: 1px solid black;" align="center" name="charts">
                <canvas id="chartAlerts"></canvas>
                <hr/>
                <a class="asLink" href="{% url 'AgentRoot:general_monitor' %}" title="Monitoring All Logs">GENERATED ALERTS</a>
                <data id="{{alerts_chart_labels}}" value="{{alerts_chart_values}}" style="display:none;">horizontalBar</data>
            </div>

            <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12 shadowBox" style="border-right: 1px solid black;" align="center" name="charts">
                <canvas id="chartLogsElastic"></canvas>
                <hr/>
                <a class="asLink" href="{% url 'AgentRoot:log_monitoring' %}" title="Monitoring All Logs">TOTAL LOGS COLLECTED</a>
                <data id="{{LogsElastic_chart_labels}}" value="{{LogsElastic_chart_values}}" style="display:none;">doughnut</data>
            </div>
            <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12 shadowBox" style="border-right: 1px solid black;" align="center" name="charts">
                <canvas id="chartLocation"></canvas>
                <hr/>
                <a class="asLink" href="{% url 'inventories:locations' %}">LOCATIONS</a>
                <data id="{{location_chart_labels}}" value="{{location_chart_values}}" style="display:none;">doughnut</data>
            </div>
        </div>
    </div>

    <br /><hr />

    <div class="row justify-content-center" id="incidentsHeader">
            <div class="col-md-10 col-sm-5"><legend>Detections</legend></div>
            <div class="col-md-2 col-sm-1">
                    <div class="row" align="right">
                            <a class="btn btn-sm btn-outline-secondary circle" name="incidentsFrame" id="incidentsPage"
                                    type="button" href="{% url 'AgentRoot:incidents_home' %}" title="Open incidents List Page"
                                    target="_blank">
                                    &#9776;
                            </a>
                            <span style="padding:2px;"></span>
                            <button class="btn btn-sm btn-outline-secondary circle" name="incidentsFrame" id="incidentsRefresh"
                                    onclick="refreshFlow(this)" title="Refresh Detection List">
                                    &#8635;
                            </button>
                            <span style="padding:2px;"></span>
                            <button class="btn btn-sm btn-outline-secondary circle" name="incidentsFrame" id="incidentsChart"
                                    onclick="open_close(this)" title="Close Content">
<!--                                        &#709;-->
                                    &#8722;
                            </button>
                    </div>
            </div>
    </div>
    <br />
    <div class="row justify-content-center" id="incidentsDiv">
            <iframe class="rcframe" id="incidentsFrame" src="{% url 'AgentRoot:incidents_home' %}" frameborder="0"></iframe>
    </div>

    <br /><hr />

<!--    <div class="row justify-content-center" id="rootCauseHeader">-->
<!--            <div class="col-md-10 col-sm-5">Anomaly Detections and Root - Cause Relationships</div>-->
<!--            <div class="col-md-2 col-sm-1">-->
<!--                    <div class="row" align="right">-->
<!--                            <a class="btn btn-sm btn-outline-secondary circle" name="rootCauseFrame" id="rcFlowPage"-->
<!--                                    type="button" href="{% url 'AgentRoot:rc_flowing' %}" title="Open Detection List Page"-->
<!--                                    target="_blank">-->
<!--                                    &#9776;-->
<!--                            </a>-->
<!--                            <span style="padding:2px;"></span>-->
<!--                            <button class="btn btn-sm btn-outline-secondary circle" name="rootCauseFrame" id="rcFlowRefresh"-->
<!--                                    onclick="refreshFlow(this)" title="Refresh Detection List">-->
<!--                                    &#8635;-->
<!--                            </button>-->
<!--                            <span style="padding:2px;"></span>-->
<!--                            <button class="btn btn-sm btn-outline-secondary circle" name="rootCauseFrame" id="rcFlowChart"-->
<!--                                    onclick="open_close(this)" title="Close Content">-->
<!--&lt;!&ndash;                                        &#709;&ndash;&gt;-->
<!--                                    &#8722;-->
<!--                            </button>-->
<!--                    </div>-->
<!--            </div>-->
<!--    </div>-->
<!--    <br />-->
<!--    <div class="row justify-content-center" id="rootCauseDiv">-->
<!--            <iframe class="rcframe shadowBox" id="rootCauseFrame" src="{% url 'AgentRoot:rc_flowing' %}" frameborder="0"></iframe>-->
<!--    </div>-->

<!--    <br /><hr />-->

<!--        <div class="row justify-content-center" id="reportSelectionHeader">-->

<!--                <div class="col-md-11 col-sm-5">Design A Report Type You Need</div>-->
<!--                <div class="col-md-1 col-sm-1">-->
<!--                        <button class="btn btn-sm btn-outline-secondary circle" name="reportSelectionDiv"-->
<!--                                id="reportSelections" onclick="open_close(this)" title="See Content">-->
<!--&lt;!&ndash;                                &#10094;&ndash;&gt;-->
<!--                            	&#x002B;-->
<!--                        </button>-->
<!--                </div>-->

<!--        </div>-->
<!--        <br />-->
<!--        <div class="row justify-content-center" name="homeScreen" id="reportSelectionDiv" style="display:none;">-->
<!--                <div class="col-sm-12 col-md-4 col-lg-3">-->
<!--                        <a href="{% url 'inventories:module_home' %}">Report Module to Create New Report Type</a>-->
<!--                </div>-->
<!--                <div class="col-sm-12 col-md-4 col-lg-3">-->
<!--                        <a href="{% url 'inventories:report_list' %}">Existing Report Type Records</a>-->
<!--                </div>-->
<!--        </div>-->
<!--        <br /><hr />-->

</div>

{% endblock %}

templates/news.html
{% if newsList %}
    <div class="container-fluid">
        {% for news in newsList %}
            <div class="container newsframe-{{news.0}}">
                <span class="newsframeClose" aria-hidden="true" onclick="$(this).parent().hide();">&times;  | </span>
                <span class="newsframeSpan">{{ news.1|safe }}</span>
            </div>
            <br />
        {% endfor %}
        <br />
    </div>
{% endif %}