accounts/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from accounts.views import *

app_name = 'accounts'

urlpatterns = [
    # path('', ),
    # path('register/', accounts_register, name='accounts_register'),
    path('login/', accounts_login, name='accounts_login'),
    path('logout/', accounts_logout, name='accounts_logout'),
    path('change/', accounts_change_password, name='accounts_change_password'),
    path('license/', add_license, name='add_license'),

]

inventories/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from inventories.views import *

app_name = 'inventories'

urlpatterns = [
    path('module/', module_home, name='module_home'),
    path('module/report', module_report, name='module_report'),
    path('module/reports', report_list, name='report_list'),
    path('networks/', networks, name='networks'),
    # path('devices/', network_devices, name='devices'),
    path('monitor/devices/', network_devices, name='devices'),
    path('locations/', locations, name='locations'),
    path('logs/', logs, name='logs'),
    path('anomalies/', anomalies, name='anomalies'),
    # path('anomalies/logs', anomaly_logs, name='anomaly_logs'),
    path('system_users/', system_users, name='system_users'),
    path('root_cause/', rc_graph_list, name='rc_graph_list'),
    path('add_device_driver/', add_device_driver, name='add_device_driver'),

    re_path(r'^networks/(?P<id>[\w-]+)/$', network_detail, name='network_detail'),
    # re_path(r'^devices/(?P<id>[\w-]+)/$', device_detail, name='device_detail'),
    re_path(r'^monitor/devices/(?P<id>[\w-]+)/$', device_detail, name='device_detail'),
    re_path(r'^locations/(?P<id>[\w-]+)/$', location_detail, name='location_detail'),
    re_path(r'^logs/(?P<id>[\w-]+)/$', log_detail, name='log_detail'),
    re_path(r'^logs/log_source/(?P<id>[\w-]+)/$', logs_for_source, name='logs_for_source'),
    re_path(r'^anomalies/(?P<id>[\w-]+)/$', anomaly_detail, name='anomaly_detail'),
    re_path(r'^anomalies/logs/(?P<id>[\w-]+)/$', anomaly_logs, name='anomaly_logs'),
    re_path(r'^root_cause/(?P<id>[\w-]+)/$', rc_graph_detail, name='rc_graph_detail'),
    re_path(r'^module/report/(?P<id>[\w-]+)/$', report_detail, name='report_detail'),
    re_path(r'^module/report/(?P<id>[\w-]+)/delete/', delete_report_type, name='delete_report_type'),

]

inventories/forms.py
import logging

from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field
from crispy_forms.bootstrap import StrictButton

logger = logging.getLogger('views')


class ReportModulePrepare(forms.Form):
    pass


class AddDriver(forms.Form):
    driver_file = forms.FileField()

    def __init__(self, *args, **kwargs):
        super(AddDriver, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_name = 'driverLoad'
        self.helper.form_id = 'driverLoad'
        self.helper.form_class = 'form-horizontal'
        self.helper.form_method = 'POST'
        self.helper.enctype = "multipart/form-data"
        # self.helper.form_action = ''
        # self.helper.label_class = 'col-md-3'
        self.helper.field_class = 'col-md-12'
        self.helper.layout = Layout(
            Field('driver_file', style="font-size:9pt;z-index:3;"),
            StrictButton('&#x271A; LOAD', css_class='btn btn-sm btn-outline-info col-md-12', type='submit',
                         style="font-size:9pt;"),
        )

    def clean(self):
        _file = self.cleaned_data.get('driver_file')
        logger.debug(f"file : {_file}")
        # logger.debug(f"file name split : {str(_file).endswith('tar.gz')}")
        file_name_parts = str(_file).split(".")
        logger.debug(f"file name split : {file_name_parts}")
        # file_extension = None
        # if len(file_name_parts) == 2:
        #     file_extension = file_name_parts[-1]
        # elif len(file_name_parts) > 2:
        #     file_extension = file_name_parts[-2]+"."+file_name_parts[-1]
        # if file_extension and file_extension == "tar.gz":
        #     logger.debug(f"extension : {file_extension}")
        if str(_file).endswith('tar.gz') or str(_file).endswith('tar'):
            logger.debug(f"Valid file : {str(_file)}")
        elif str(_file) != "None":
            logger.warning(f"Trying to add {str(_file)} Not valid driver file!!")
            raise forms.ValidationError('Not a valid driver file')
        else:
            raise forms.ValidationError('Not a valid driver file')
        return _file

inventories/views.py
import _thread
import io
import locale
# import json
# import math
import tarfile
import tracemalloc

import django.apps
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.clickjacking import xframe_options_sameorigin

from ATIBAreport.decorators import licence_required
from ATIBAreport.graph_generator import report_main_grid
from ATIBAreport.project_common import *
from ATIBAreport.reachjava import take_logs_from_elastic_with_java
from ATIBAreport.setting_files.basesettings import MEDIA_ROOT
from AgentRoot.models import *
# from accounts.models import User
from inventories.forms import AddDriver
from inventories.models import *

locale.setlocale(locale.LC_ALL, locale='tr_TR.utf8')

# we need it for GUI based errors like self.tk.call('image', 'delete', self.name) about tkinter process
# RuntimeError: main thread is not in main loop
matplotlib.use('Agg')

logger = logging.getLogger('views')
timer = logging.getLogger('timer')
memory_tracer = logging.getLogger('memorytracer')

globalBool = True
globalObjectList = []
globalObject = None
globalVariable = None


def template_message_show(key, message_type, message_content):
    """
    use to create template messages with message type and content, its useful for object_listing function notifications
    """
    if message_type == "info":
        template_message = messages.info(key, message_content)
    elif message_type == "warning":
        template_message = messages.warning(key, message_content)
    elif message_type == "error":
        template_message = messages.error(key, message_content)
    elif message_type == "success":
        template_message = messages.success(key, message_content)
    else:
        template_message = messages.error(key, message_content)

    return template_message


@licence_required
@login_required
def networks(request):
    time_triggered = datetime.datetime.now()
    if tracemalloc.is_tracing():
        tracemalloc.stop()
    tracemalloc.start()
    systemNetworks = object_listing(NetworkParameters)
    networkList = systemNetworks["list"]
    template_message_show(request, systemNetworks["type"], systemNetworks["message"])

    paginator = Paginator(networkList, 20)
    page = request.GET.get('page')
    try:
        networkList = paginator.page(page)
    except PageNotAnInteger:
        networkList = paginator.page(1)
    except EmptyPage:
        networkList = paginator.page(paginator.num_pages)

    context = {
        'route': 'general',
        'networkList': networkList,
    }
    # memory usage logging with memory_tracer
    top_stats = tracemalloc.take_snapshot().statistics('lineno')
    total_size, unit = take_memory_usage(top_stats)
    logger.info(f"Memory allocation  {total_size} {unit}")
    memory_tracer.info(f"{total_size}")
    tracemalloc.stop()
    timer.debug(f"{(datetime.datetime.now() - time_triggered).total_seconds()}")
    return render(request, 'inventories/networks.html', context)


@licence_required
@login_required
def network_detail(request, id):
    time_triggered = datetime.datetime.now()
    if tracemalloc.is_tracing():
        tracemalloc.stop()
    tracemalloc.start()
    try:
        systemNetwork = NetworkParameters.objects.get(id=id)
    except ObjectDoesNotExist:
        return redirect('home')
    context = {
        'route': 'detail',
        'systemNetwork': systemNetwork,
    }
    # memory usage logging with memory_tracer
    top_stats = tracemalloc.take_snapshot().statistics('lineno')
    total_size, unit = take_memory_usage(top_stats)
    logger.info(f"Memory allocation  {total_size} {unit}")
    memory_tracer.info(f"{total_size}")
    tracemalloc.stop()
    timer.debug(f"{(datetime.datetime.now() - time_triggered).total_seconds()}")
    return render(request, 'inventories/networks.html', context)


@licence_required
@login_required
def network_devices(request):
    time_triggered = datetime.datetime.now()
    if tracemalloc.is_tracing():
        tracemalloc.stop()
    tracemalloc.start()
    try:
        deviceList = list(
            NetworkDevice.objects.filter(connectedmac=None).exclude(brand_id=None).exclude(brandModel_id=None).exclude(
                brand_id=0).exclude(brandModel_id=0))
        unsupportedDeviceList = list(
            NetworkDevice.objects.filter(brand_id=None).filter(connectedmac=None)) + list(
            NetworkDevice.objects.filter(brand_id=0).filter(connectedmac=None)) + list(
            NetworkDevice.objects.filter(brandModel_id=0).filter(connectedmac=None)) + list(
            NetworkDevice.objects.filter(brandModel_id=None).filter(connectedmac=None))
        unsupportedDeviceList = list(set(unsupportedDeviceList))
        template_message_show(request, "success", f"Successfully finished for {NetworkDevice.objects.count()} devices")
    except Exception as err:
        deviceList = []
        unsupportedDeviceList = []
        template_message_show(request, "error", f"Error occurred while getting devices : {err}")

    supported_count = len(deviceList) + len([d for device in deviceList for d in device.get_connected_devices()])
    unsupported_count = len(unsupportedDeviceList) + len(
        [d for device in unsupportedDeviceList for d in device.get_connected_devices()])

    paginator_1 = Paginator(deviceList, 20)
    s_page = request.GET.get('s_page')
    try:
        deviceList = paginator_1.page(s_page)
    except PageNotAnInteger:
        deviceList = paginator_1.page(1)
    except EmptyPage:
        deviceList = paginator_1.page(paginator_1.num_pages)

    paginator_2 = Paginator(unsupportedDeviceList, 20)
    u_page = request.GET.get('u_page')
    try:
        unsupportedDeviceList = paginator_2.page(u_page)
    except PageNotAnInteger:
        unsupportedDeviceList = paginator_2.page(1)
    except EmptyPage:
        unsupportedDeviceList = paginator_2.page(paginator_2.num_pages)

    if s_page:
        supported_style = "display:block;"
        unsupported_style = "display:none;"
    elif u_page:
        supported_style = "display:none;"
        unsupported_style = "display:block;"
    else:
        supported_style = ""
        unsupported_style = "display:none;"

    context = {
        'route': 'general', 'supported_count': supported_count, 'unsupported_count': unsupported_count,
        'deviceList': deviceList, 'unsupportedDeviceList': unsupportedDeviceList,
        'supported_style': supported_style, 'unsupported_style': unsupported_style,
    }
    # memory usage logging with memory_tracer
    top_stats = tracemalloc.take_snapshot().statistics('lineno')
    total_size, unit = take_memory_usage(top_stats)
    logger.info(f"Memory allocation  {total_size} {unit}")
    memory_tracer.info(f"{total_size}")
    tracemalloc.stop()
    timer.debug(f"{(datetime.datetime.now() - time_triggered).total_seconds()}")
    return render(request, 'inventories/devices.html', context)


@licence_required
@login_required
@xframe_options_sameorigin
@csrf_exempt
def device_detail(request, id):
    time_triggered = datetime.datetime.now()
    if tracemalloc.is_tracing():
        tracemalloc.stop()
    tracemalloc.start()
    global globalObject
    if globalObject:
        if isinstance(globalObject, NetworkDevice) and globalObject.id == id:
            device = globalObject
        else:
            try:
                device = NetworkDevice.objects.get(id=id)
                globalObject = device
            except ObjectDoesNotExist:
                return redirect('AgentRoot:general_monitor')
    else:
        try:
            device = NetworkDevice.objects.get(id=id)
            globalObject = device
        except ObjectDoesNotExist:
            return redirect('AgentRoot:general_monitor')

    # logger.debug(f"{mac_to_simplified(device.macAddress_id)}")

    context = {
        'route': 'detail',
        'device': device,
    }
    # memory usage logging with memory_tracer
    top_stats = tracemalloc.take_snapshot().statistics('lineno')
    total_size, unit = take_memory_usage(top_stats)
    logger.info(f"Memory allocation  {total_size} {unit}")
    memory_tracer.info(f"{total_size}")
    tracemalloc.stop()
    timer.debug(f"{(datetime.datetime.now() - time_triggered).total_seconds()}")
    return render(request, 'inventories/devices.html', context)


@licence_required
@login_required
def locations(request):
    time_triggered = datetime.datetime.now()
    if tracemalloc.is_tracing():
        tracemalloc.stop()
    tracemalloc.start()
    systemLocations = object_listing(DevLocations)
    locationList = systemLocations["list"]
    template_message_show(request, systemLocations["type"], systemLocations["message"])

    paginator = Paginator(locationList, 20)
    page = request.GET.get('page')
    try:
        locationList = paginator.page(page)
    except PageNotAnInteger:
        locationList = paginator.page(1)
    except EmptyPage:
        locationList = paginator.page(paginator.num_pages)

    context = {
        'route': 'general',
        'locationList': locationList,
    }
    # memory usage logging with memory_tracer
    top_stats = tracemalloc.take_snapshot().statistics('lineno')
    total_size, unit = take_memory_usage(top_stats)
    logger.info(f"Memory allocation  {total_size} {unit}")
    memory_tracer.info(f"{total_size}")
    tracemalloc.stop()
    timer.debug(f"{(datetime.datetime.now() - time_triggered).total_seconds()}")
    return render(request, 'inventories/locations.html', context)


@licence_required
@login_required
def location_detail(request, id):
    time_triggered = datetime.datetime.now()
    if tracemalloc.is_tracing():
        tracemalloc.stop()
    tracemalloc.start()
    global globalObject
    if globalObject:

templates/inventories/anomalies.html
{% extends 'base.html' %}

{% load static %}
<link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

{% block titleBlock %}

    Networks {{ block.super }}

{% endblock %}

{% block bodyBlock %}



{% if route == "general" %}

    <div class="innerBodies">
        <table class="table table-striped table-sm table-hover">
            <caption>ANOMALIES</caption>
            <thead class="thead-light">
                <tr>
                    <th>CAUSE</th>
                    <th colspan="3">RELATED ANOMALY LOGS</th>
                    <th>USER FEEDBACK</th>
                </tr>
            </thead>
            <tbody>
                {% for anomaly in anomalyList %}
                <tr>
                    <td><a href="{{ anomaly.get_absolute_url }}">{{ anomaly.causeeffect }}</a></td>
                    <td><i>{{ anomaly.anomalyLog_id }}</i></td>
                    <td><i>with</i></td>
                    <td><i>{{ anomaly.subAnomalyLog_id }}</i></td>
                    <td>{% if  anomaly.userfeedback == true %}&#x2713;{% else %}&#x2717;{% endif %}</td>

                </tr>
                {% endfor %}
            </tbody>

        </table>

        <div></div>

        <hr />
        {# PAGINATION #}
        <div class="pagination">
            <span class="step-links">
                {% if anomalyList.has_previous %}
                    <a href="?page=1">&laquo; jump to first </a>/
                    <a href="?page={{ anomalyList.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"> previous </a>/
                {% endif %}

                <span class="current">
                    <i>{{ anomalyList.number }}. of {{ anomalyList.paginator.num_pages }} pages </i>
                </span>

                {% if anomalyList.has_next %}
                    /<a href="?page={{ anomalyList.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"> next </a>
                    /<a href="?page={{ anomalyList.paginator.num_pages }}"> jump to last &raquo;</a>
                {% endif %}
            </span>
        </div>{# /pagination #}

    </div>



{% elif route == "detail" %}

<div class="container-fluid innerBodies">
    <table class="table table-striped table-sm table-hover">
        <caption>ANOMALY DETAILS</caption>
        <thead class="thead-light">
            <tr>
                <th>Device Name</th>
                <th><a href="{{ device.get_absolute_url }}">{{ device.devicename }}</a></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Device IP Address</td>
                <td>{{ anomaly.anomalyLog.deviceip }}</td>
            </tr>
            <tr>
                <td>Device Unique ID</td>
                <td>{{ anomaly.anomalyLog.get_device.uniqueid }}</td>
            </tr>
            <tr>
                <td>Cause Effect Result</td>
                <td>{{ anomaly.causeeffect }}</td>
            </tr>
            <tr>
                <td><a href="{{ anomaly.anomalyLog.get_anomaly_logs_url }}">Related Log 1</a></td>
                <td><a href="{{ anomaly.anomalyLog.get_anomaly_logs_url }}">{{ anomaly.anomalyLog_id }}</a></td>
            </tr>
            <tr>
                <td>Related Log 1 Anomaly Type</td>
                <td>{{ anomaly.anomalyLog.anomalytype }}</td>
            </tr>
            <tr>
                <td>Related Log 1 Creation Date</td>
                <td>{{ anomaly.anomalyLog.credate }}</td>
            </tr>
            <tr>
                <td><a href="{{ anomaly.subAnomalyLog.get_anomaly_logs_url }}">Related Log 2</a></td>
                <td><a href="{{ anomaly.subAnomalyLog.get_anomaly_logs_url }}">{{ anomaly.subAnomalyLog_id }}</a></td>
            </tr>
            <tr>
                <td>Related Log 2 Anomaly Type</td>
                <td>{{ anomaly.subAnomalyLog.anomalytype }}</td>
            </tr>
            <tr>
                <td>Related Log 2 Creation Date</td>
                <td>{{ anomaly.subAnomalyLog.credate }}</td>
            </tr>
        </tbody>
    </table>

    <div></div>
    <div><a href="{% url 'inventories:anomalies' %}"> BACK TO ANOMALIES </a></div>
</div>


{% endif %}




{% endblock %}

templates/inventories/forms.html
{% extends 'base.html' %}

{% load static %}
<link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

{% block titleBlock %}

    Reporting Module {{ block.super }}

{% endblock %}

{% block bodyBlock %}



{% if route == "general" %}

    <div class="container-fluid innerBodies">Calculating some datas</div>

    <div class="innerBodies">



        <div></div>

        <hr />
        <button class="btn btn-outline-primary btn-sm floating-right" id="save" type="button" onclick="get_results()">
            SEE ALL CHOICES
        </button>

    </div>



{% elif route == "detail" %}




{% endif %}




{% endblock %}

templates/inventories/locations.html
{% extends 'base.html' %}

{% load static %}
<link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

{% block titleBlock %}

    Locations {{ block.super }}

{% endblock %}

{% block bodyBlock %}

{% if route == "general" %}

    <div class="innerBodies">
        <table class="table table-striped table-sm table-hover">
            <caption>NETWORK LOCATIONS</caption>
            <thead class="thead-light">
                <tr>
                    <th>LOCATION NAME</th>
                    <th>LOCATION CODE</th>
                    <th>LOCATION GROUP NAME</th>
                </tr>
            </thead>
            <tbody>
                {% for location in locationList %}
                <tr>
                    <td><a href="{{ location.get_absolute_url }}">{{ location.locationname }}</a></td>
                    <td>{{ location.locationcode }}</td>
                    <td>{% if location.locationGroup_id != null %}{{ location.locationGroup.locationgroupname }}{% else %} {% endif %}</td>
                </tr>
                {% endfor %}
            </tbody>

        </table>

        <hr />
        {# PAGINATION #}
        <div class="pagination">
            <span class="step-links">
                {% if locationList.has_previous %}
                    <a href="?page=1">&laquo; jump to first </a>/
                    <a href="?page={{ locationList.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"> previous </a>/
                {% endif %}

                <span class="current">
                    <i>{{ locationList.number }}. of {{ locationList.paginator.num_pages }} pages </i>
                </span>

                {% if locationList.has_next %}
                    /<a href="?page={{ locationList.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"> next </a>
                    /<a href="?page={{ locationList.paginator.num_pages }}"> jump to last &raquo;</a>
                {% endif %}
            </span>
        </div>{# /pagination #}

    </div>

{% elif route == "detail" %}

<div class="container-fluid innerBodies">
    <table class="table table-striped table-sm table-hover">
        <caption>NETWORK LOCATION</caption>
        <thead class="thead-light">
            <tr>
                <th>Location Name</th>
                <th>{{ location.locationname }}</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Location Code</td>
                <td>{{ location.locationcode}}</td>
            </tr>
            <tr>
                <td>Location Group Name</td>
                <td>{{ location.locationGroup.locationgroupname }}</td>
            </tr>
            <tr>
                <td>Location Group Code</td>
                <td>{{ location.locationGroup.locationgroupcode }}</td>
            </tr>
        </tbody>
    </table>

    <div></div>
    <div><a href="{% url 'inventories:locations' %}"> BACK TO LOCATIONS </a></div>

</div>

{% endif %}

{% endblock %}

templates/inventories/module.html
{% extends 'base.html' %}

{% load static %}
<link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

{% block titleBlock %}

    Reporting Module {{ block.super }}

{% endblock %}

{% block bodyBlock %}



{% if route == "general" %}

<div class="container-fluid innerBodies">Get Reports AS U WISH</div>

<div class="innerBodies">
    <div class="row justify-content-center"><h4>{{ caption }}</h4></div>
    <div class="row">
        <div class="col col-md-4 col-sm-4">DATA TABLE</div>
        <div class="col col-md-4 col-sm-4">COLUMNS</div>
        <div class="col col-md-4 col-sm-4">CHOICES</div>
    </div>
    <hr>
    <form id="report_test" method="POST" action="{% url 'inventories:module_report' %}" name="report_choices">
        {% csrf_token %}
        <div class="row">
            <div class="col col-md-4 col-sm-4" name="classesDiv" id="classList">
                <select onchange="get_list_2(this.value)" name="class_names">
                    {% for model, fields in modelNameList %}

                            {% if forloop.counter == 1 %}
                                <option value="{{model}}">{{ model }}</option>
                                <option disabled>--------------------------</option>
                            {% else %}
                                {% if fields|length > 0 %}
                                    <option value="{{model}}">{{ model }}</option>
                                {% endif %}
                            {% endif %}
                    {% endfor %}
                </select>
            </div>
            <div class="col col-md-4 col-sm-4" name="columnsDiv" id="columnList">
                {% for model, fields in modelNameList %}
                    <div style="display:none;" id="{{model}}" name="fieldsList">
                        {% for field, verbose in fields %}
                                <input type="checkbox" onclick="get_value(this)" name="{{ model }}" class="form-check-input" value="{{field}}" id="{{model}}_index_{{forloop.counter|add:-1}}">
                                    <label class="form-check-label" for="{{model}}_index_{{forloop.counter|add:-1}}">
                                        {{verbose}}
                                    </label>
                                </input>
                                <br>
                        {% endfor %}
                    </div>

                {% endfor %}
            </div>
            <div class="col col-md-4 col-sm-4" name="selectionsDiv" id="selectionList">
                <div name="choices" id="viewChoices"></div>
            </div>
        </div>
        <input class="btn btn-outline-warning btn-sm floating-right" type="submit" value="SAVE CHOICES" />
    </form>
    <hr>
<!--    <button class="btn btn-outline-primary btn-sm " id="save" type="button" onclick="get_results()">-->
<!--        SEE ALL CHOICES-->
<!--    </button>-->
    <div class="container-fluid" id="overall">
        <span>Report will be prepared for choices : </span>
        <span id="overall_result" style="color:blue;">

        </span>
    </div>
</div>

<script type="text/javascript" lang="javascript">
    function get_value(element){
        var cBox = element;
        var id = element.name;
        var result_area = document.getElementById("viewChoices");
        var result = element.value + "<br>";
        if(cBox.checked == true){
            result_area.innerHTML += result;
        } else {
            result_area.innerHTML = result_area.innerHTML.replace(result, "");
        }
    }

    function get_list_2(value) {
        //console.log(value);
        var tds = document.getElementsByName("fieldsList");
        //console.log(tds[0].id);
        for(var i=0; i<tds.length; i++) {
            //console.log(tds[i].id);
            if(tds[i].id == value) {
                tds[i].style = "display:block;";
            }else {
                tds[i].style = "display:none;";
            }
        }
    }

    // function for see choices button, bu now inactive;
    function get_results() {
        var choices_list = [];
        var elements = document.getElementsByName("choices");
        var element;
        for(var i=0; i<elements.length; i++){
            element = elements[i];
            if(element.innerHTML == "") {
            } else {
                listOf = element.innerHTML.split("<br>");
                for(var j=0; j<listOf.length; j++){
                    if(listOf[j] == ""){}else{choices_list.push(listOf[j]);}
                }
            }
        }
        if(confirm("Your choices : \n"+choices_list)){document.getElementById("overall_result").innerHTML = choices_list;}else {}
    }

</script>

{% elif route == "detail" %}




{% endif %}




{% endblock %}

templates/inventories/networks.html
{% extends 'base.html' %}

{% load static %}
<link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

{% block titleBlock %}

    Networks {{ block.super }}

{% endblock %}

{% block bodyBlock %}



{% if route == "general" %}

    <div class="innerBodies">
        <table class="table table-striped table-sm table-hover">
            <caption>NETWORKS</caption>
            <thead class="thead-light">
                <tr>
                    <th>NETWORK NAME</th>
                    <th>IP ADDRESS</th>
                    <th>SUB NETWORK MASK</th>
                </tr>
            </thead>
            <tbody>
                {% for network in networkList %}
                <tr>
                    <td><a href="{{ network.get_absolute_url }}">{{ network.networkname }}</a></td>
                    <td>{{ network.ipaddress }}</td>
                    <td>{{ network.subnetmask }}</td>

                </tr>
                {% endfor %}
            </tbody>

        </table>

        <div></div>

        <hr />
        {# PAGINATION #}
        <div class="pagination">
            <span class="step-links">
                {% if networkList.has_previous %}
                    <a href="?page=1">&laquo; jump to first </a>/
                    <a href="?page={{ networkList.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"> previous </a>/
                {% endif %}

                <span class="current">
                    <i>{{ networkList.number }}. of {{ networkList.paginator.num_pages }} pages </i>
                </span>

                {% if networkList.has_next %}
                    /<a href="?page={{ networkList.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"> next </a>
                    /<a href="?page={{ networkList.paginator.num_pages }}"> jump to last &raquo;</a>
                {% endif %}
            </span>
        </div>{# /pagination #}

    </div>



{% elif route == "detail" %}

<div class="container-fluid innerBodies">
    <table class="table table-striped table-sm table-hover">
        <caption>NETWORK DETAILS</caption>
        <thead class="thead-light">
            <tr>
                <th>Name</th>
                <th>{{ systemNetwork.networkname }}</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>IP Address</td>
                <td>{{systemNetwork.ipaddress}}</td>
            </tr>
            <tr>
                <td>Sub Network Mask</td>
                <td>{{systemNetwork.subnetmask}}</td>
            </tr>
        </tbody>
    </table>

    <div></div>
    <div><a href="{% url 'inventories:networks' %}"> BACK TO NETWORKS </a></div>





</div>


{% endif %}




{% endblock %}